// Package model holds the structs that mirror the database ERD, one type per
// table, plus the column enum types those structs are declared in terms of.
//
// It contains no behaviour. Validation, display labels and score banding used
// to hang off these types as methods; they now live in the layer that uses
// them (see internal/service and internal/delivery/http/handler). Non-table
// shapes - filters, AI request/response envelopes, ingestion previews - live
// in internal/dto. Keeping this package to data alone means every layer can
// import it without inheriting a dependency, and a reader can take the file
// list here as the schema.
//
// Every field carries a json tag so a model round-trips through an API or a
// JSONB column without a parallel set of wire structs.
//
// Primary keys are uuid.UUID, generated by the database (gen_random_uuid())
// and written back on insert. The zero uuid.UUID is "unset" and is what
// validation checks for; nullable references are *uuid.UUID.
package model
